** 0.2.4: HotFix
- Solved bugs in the LibFILDSIM.find_strike_map routine, the fildsim options were not updated properly
- Updated FILDSIM example following new f90nml requirements

** 0.2.3: Filter for video object
- *Included requested feature*: median filter added to the filter_frames method of the video class (closes #47)
- *Closes #45* Now the rmin, rmax, pmin, pmax represent the output vector when we want the remap, not the input edges (:-()
- 'Clean' a bit the method 'find_strike_map' from the FILDSIM library, now a loop is used to run over FILDSIM namelist
- Included Gaussian filter for the video frames
- Reordered examples
- Simplified plotting options in TimeTrace.plot_single()
- Improved TimeTrace.plot_all(), now they share x axis so zoom is better

** 0.2.2: Debugging
- *BUG_SOLVED* in the plot_vessel function, the factor from m to cm was 10 instead of 100!
- *BUG_SOLVED* rotation of the vessel was not passed from the plot_vessel routine to the method which calculate the vessel coordinates
- *BUG_SOLVED* Solved bug when the requested interval to average the noise was not in the file (issue #46)

** 0.2.1: FIDASIM implementation
- First routines to read FIDASIM output added, (thanks Pilar :-)) Although some work still needed in that module this is not completelly checked
- Updated Readme following nice example of iHIBP
- Calibration used in the remapping is saved in the remapping options, such that future comparisons of remapped data is easier
- plot_profiles_in_time of the video object allows now to pass the min and max of the scale as inputs
- *Included requested feature* First implementation of issue #41

** 0.2.0: Strike Maps reordering
- p1D_shaded_error updated with the possibility of plotting the central line
- Updated gitignore to ignore a folder call 'MyRoutines' for the user to have its own routines
- Updated the paths to strike maps, now two libraries will be used: Remap 'low' number of markers, 'Tomography' high number of markers
- Updated namelist format, now the suite follows the criteria given in the f90nml module
- Added GNU license

** 0.1.9: Spectrograms
- First spectrogram function added, first step towards the fast channel analysis
- Better examples included
- Better checking of wether we are in AUG or not
- Now the remapping of the whole shot can be done using a given strike map

** 0.1.8: Reverse FILD
- IB sign were included to include the proper pitch definition in FILDSIM even with the reverse field
- *BUG_SOLVED*: Solve a bug which forced the remap to ignore theta and phi if just one of the strike maps was not found
- Included the RealBPP in the exported remap data

** 0.1.7: Improve reading/writting
- Solved the issue in the init due to new iHIBPsim libraries
- Included a check to not overwrite files, now if one of the saving routines try to save a file which exist, it will open a window to give to the user the chance to change the name
- Added also a similar function to open files in case it does not find the name, it will pop-up a window
- Improved the checking to test we are in AUG
- Add a method to integrate the remapped frames in the desired range radius-pitch (arbitrary shapes allowed via roi)

** 0.1.6: What's new?
- Added possibility of loadind the used ROIs
- Added the posibility of plotting each individual time trace
- Added general routine to load the created ncdf files
- Suppresed remapped slider plotting in the video object, it was too buggy, new one will come with tkinter

** 0.1.5: What's new?
- Now the remap_all_loaded_frames_FILD first calculate all theta and phi and see how many strike maps must be calculated. The user can decide wheter if perform the FILDSIM calculation or just take a single strike map
- Added the possibility of remaping with a ROI. Also export the ROI

** 0.1.4: What is new?
- iHIBP routines to interact with the tracker and iHIBPsim, first round
