** 0.8.0 Future Version
This verison was not released, this is just a warning about things which will be deprecated:
- The Strikes object of the FILDSIM code, use the Common object instead, already available and working better
- StrikeMap.plot_strike_points() will be deleted. Please use StrikeMap.strike_points.scatter() instead, much better, with more flexibility and options

** 0.7.1 Uncertainties in fits and angles in execution:
*** LibMap:
- The fitting routines now return also the uncertainties
- 'Gyroradius_uncertainty' and 'Pitch_uncertainty' were added to the StrikeMap.resolution dictionary
- Strike Map object recognizes which code generated the StrikeMap (thanks to a number in the header which SINPA introduces)
- 'code' and 'version' attributes were added to the Strike Map object
- XI, nXI and uniqueXI attributes were added to the FILD StrikeMap object, as a starting point for we merging of INPA and FILD processing
- The StrikeMap object uses now the new strike points object, common of FILD and SINPA
*** LibVideoFiles:
- Included plt_frame_remap() to plot remapped frames
*** SINPA
- Added a routine in the SINPA execution library to calculate the FILD orientation following the new criteria
- Recovered the SINPA geometry library which was eliminated by mistake, the calculate rotation matrix is again there
- field object from the common library of the simulation codes now includes a method to generate the field for SINPA given theta and phi, the same 2 angles defined in FILDSIM
*** Bug fixed:
- Fixed bug if an old version of Shapely was installed
- Fixed a small bug in the calculation of FILD orientation

** 0.7.0 Common libraries for simulation codes
*** Equilibrium
- Included routine to retrieve the flux surface coordinates (R, z).
*** i-HIBPsim namelists [iHIBPsim/nml.py]
- Routines to generate generic namelists for the iHIBPsim code [make_namelist]
- Routines to check consistency of namelists [check_namelist].
- Routine to check if the files needed for a run of iHIBPsim are available [check_files]
*** i-HIBPsim execution wrapper [iHIBPsim/execute.py]
- prepareRun() wrapper to generate a simple run for iHIBPsim.
- run_ihibpsim() wrapper to run the code properly. No cluster version available.
*** i-HIBPsim geometry library [iHIBPsim/geom.py]
- Included particularities of the i-HIBPsim beam model in the library.
- Routines to generate beam lines, divergencies limits...
- gaussian_beam class to handle and contain all the data for a i-HIBPsim beam and plot it.
- geom class contains all the i-HIBPsim geometry: beam, head and scintillator plate and routines to plot it.
*** i-HIBPsim beam GUI [GUIs/i-HIBP_beam.py]
- First GUI app for plotting the beam geometry. To be improved with Qt version.
- GUI has to be run by : "run Examples/Others/ihibp_beam_gui.py"
*** LibVideo
- Plotting frames and remaps allows for the possibility of using log scale in the colorbar. Just set scale='log'
- Improved efficiency of the counting of saturated frames thanks to build in methods
- flag 'make_copy' from the filter method of the video file was rename to 'flag_copy' to be consistent with the noise subtraction case
- LibVideo split in individual libraries. The complete library was almost 3k lines of code. Now individual libraries are written for each type of archive
- BasicVideoObject created. This object is now the parent class for the INPA, FILD and iHIBP videos. IT just contain the skeleton to read frames, filter them and subtract noise (which is common for all diagnostics). In the future, it will include distortion correction
- FILDVideo object created. Is just the child class of BasicVideoObject with all FILD routines
*** LibPlotting
- clean3Daxis() included: It removes the ugly panes that matplotlib puts by default in 3d plots
- axisEqual3D() set aspect ratio to equal in the 3D plot
*** Simulation codes
- A new Geometry library was added, it can read geometries from FILDSIM and SINPA code. It can plot in 3D and 2D, shaded and not shared, apply the rotation and translation to the vertex... read the documentation of the library for full detail
- A new StrikePoints object was added. Now is it exactly the same for SINPA and FILDSIM codes!. So from the end user point of veiw, post process the data from both codes is equivalent.  Old FILDSIM strike object left there as for compatibility with all users, but is not recommended
*** Deprecation
- The object Geometry from the SINPA library was deprecated. The one from the Common library for the simulations codes should be used!
*** Others
- Improved comments and documentation
- The function which read FILDSIM orbits now raise an exception if there were no orbits in the file

** 0.6.5 Interpolators and synthetic signals
- Changed to RBFInterpolator, which seems to be more stable thatn BivariateSpline (*Scipy 1.7.0 or larger is required now*)
- Most robust calculation of the synthetic signal for FILD (no bugs for fcol almost zero)
- Solve a bug in the loading of the strike map. If a StrikePointsFile was passed as argument, the code failed. (Bug introduced in version 0.6.4)
*** Deprecations
- p1D() from the plotting library was deprecated

** 0.6.4 New interpolators for SINPA and SMap upgrades
*** StrikeMap
- StrikeMap can now be initialize with fild instead of FILD (actually the comparison is lower case, so you can initialize it as FiLd if you are crazy)
- StrikeMap now is able to load strike points from the new FILDSIM format
- If there are not strike points loaded, the function StrikeMap.calculate_resolutions will try to load them
- Plot real updated to show properly the labels if the inputs are in m or cm. Labels are now a bit messy, need a bit more work in future versions
- Smap.sanity_check_resolutions() was deprecated and eliminated
- Smap.plot_resolution_fits() released. This is the new and complete way of plotting the fits performed during the resolution calculation
- Smap.calculate_resolution no longer use predefined indeces but the header object, so it will not be an issue for future changes of strike object files
- _fit_to_model__() now return also de used normalization
*** Video
- Video.subtract_noise() was upgrade, loop was eliminated, now is much faster
- Video.subtract_noise() now always return the frame used, the flag return_frame was deprecated
*** IO
- IO.save_object_pickle() was corrected. Now it does not fail when user click cancel
*** Others
- improved comments and documentations
** 0.6.3 Small improvements
- line_fit_3D was moved from the INPASIM library to the SideFuncitons one
- Change in the SINPA.Strike to accommodate the order changes in SINPA (just a couple of index changed in the header)

** 0.6.2 Small improvements
*** TimeTrace
- TimeTrace.plot_single() now shows the axis and include a print for the base line correction done

** 0.6.1
*** Mapping library
- plot_resolution allows to plot just the resolution along a given gyroradii, avoiding the 2D contour which is difficult to follow. Check index_gyr new optional variable
- plot_pix of the Scintillator object was upgraded, now 'the scintillator is closed'. Default line style is continuous and color is white
*** Video Object
- plot_frame now include by default a colorbar
*** SINPA Library
- Solved a bug when the scintillator histogram wanted to be calculated for FILD data
*** Enhance plotting
- Lib.Plotting include a function to plot a collection of lines with colors given by a colormap (collection is mapable so you can then include a colorbar)

** 0.6.0 SINPA Support and new Tomography
*** Simulation codes
- Libraries to interact with the different simulation codes (FIDASIM, FILDSIM, iHIBPsim, and SINPA) are now located in the SimulationCodes library

*** FIDASIM
- Included routines to read the npa data
- Library subdivided in read and plot
*** FILDSIM
- a new FILDSIMmarkers library was created. It contain the new object to load and plot the strike maps
- *Note*: This library imply a small change of phylosophy against previous versions. Yuo can still load and use the strike points as before from the strike map, but they are now a part from the FILDSIM library, with their own object and ploting routines.
- This change was made for an earier integration of INPA and for an easier analysis of FILDSIM strike points for FILD optimization
- Function to plot any variable of the FILDSIM strike points was added: see LibFILDSIM.Strikes.plot1D()
- Direct and easy calculation of the histogram of strike points in the scintillator was added: see LibFILDSIM.Strike.calculate_scintillator_histogram() and LibFILDSIM.Strike.plot_scintillator_histogram()
- When the FILDSIM markers are loaded, they are no longer treated like a single matrix, they are splits by pairs (gyroradius, pitch). This save memory (we do not need to save the first 2 colums of the matrix) and simplify routines as the calculation of the resolution
- The function to read the orbits was removed from the FILDSIMexecution library and moved to the FILDSIMmarkers one, inside the new orbtis object
- The same happeded with the plot orbits, which is now a part from the orbit object
*** Mapping library
- Support for SINPA strike maps was included in the mapping library
- calculate_transformation_factors was deprecated
- get_points was deprecated
- append_to_database from the database object was deprecated
- The strike points variable of the StrikeMap was completely changed, see the FILDSIM part of the changelog for a full documentation
*** SINPA
- the new Synthetic INPA code is supported
*** Tomography
- Mono dimensional tomography can be performed, examples can be found in L15
*** PC compatibility
- Included a dummy LibData in order to be able to import the suite in your personal PC. Minor modifications here and there in the import statements were done to support this
*** Others
- function Lib.LibData.AUG.plot_FILD4_trajectory(shot) renamed to Lib.LibData.AUG.plot_FILD4_trajectory(shot)
- Solved a bug in Video.find_orientation when the function was called with the remap not calculated
- Solve small bug in the plot_real routine of the strike map, before pitch label was 'Pitch [0])' and in the gyroradius one, there were () instead of []
- Vid.plot_orientation no longer set by default the font size, as that is don now when initializing the suite
- Lib.Libfildsim.plot_geometry(). Dummy bug corrected, in the title of the 3 subplot it said 'Y-Z' instead of 'X-Z'
- Default colormap in the GUIS to plot the videos is now grey scale
- Added update_case_insensitive to the Utilities library to compare dictionaries in a case insensitive way
- Added a custom path file so the user can define its own paths
- Improvements in comments + PEP8 checking
- change 'Pablo Oyola:' to 'Pablo Oyola - ' beause Pablo likes more the ' - ' notation to introduce his email
- NBI object includes now an option to plot in 3D
- Solved minor details for the first installation (regarding plotting settings initialization and AUG path)

** 0.5.8 Minor improvements
- The guess_shot of the video class will no longer give an error if the shot number can't be deduced from the file name, it will just return none
- TimeTrace.export_to_ascii() now allows to select the number of digits you want for the output. By default, just 4 digits are used.

** 0.5.7 Minor improvements
- The print netCDF routine of the io is now compatible with netCDF saved without the long _name field
- Upgraded plot_profiles in time, now the labels re-adapt when the user makes zoom

** 0.5.6 i-HIBP namelists and ELM sync routines.
- Added new sublibrary in LibData/AUG names Misc, containing FILD4 trajectories, ELM shotfile...
- Basic namelist generation for i-HIBP simulation codes library included.
- Basic library for i-HIBP beam plotting and marker generator.
- Update in the library BPZ to read and plot BEP fitting data.
- L6 example now uses the MC method
- *Bug solved* related with the single strikemap remap. Before, if you asked the single map remapping, it failed at the end when it tries to save the data, as the variable theta_used was not created, as the theta angle was not evaluated. Now it just save theta_used=0 and solved!

** 0.5.5: Minor improvements and examples
- added an example to plot a discharge overview in AUG
- calculate spectrograms of the fast channel now uses as default the scipy spectrogram function

** 0.5.4: Minor improvements
- plot_single of the TimeTrace object now no longer have default color red, so is not a problem to compare different shots. Line_par and ax_par entries of that functions were renamed to line_params and ax_params to be coherent with the rest of the suite
- new examples to analyse FILD data

** 0.5.3: Minor improvements
- Now the scan of the tomography library saves the data in each interaction (can be deactivate via inputs)
- Label can be set in the plotting of the fast channel via line_params dictionary
- *Bug solved* now the get_fast_signal() will not fail if the requested channel is a component of a numpy array
- Lib.LibData.AUG.plot_FILD4_trayectory(shot) and Lib.LibData.AUG.load_FILD4_trayectory(shot) added to load FILD4 data. First step of FILD4 disclosure
- Plotting style sheet updated, now you can choose default colors for line plotting

** 0.5.2: Minor improvements
- synthetic_signal_remap() will output the signal as a matrix [npitch, nradius] to be consistent with the remap (before it was [nradius, npitch])
- The fast channel options allows now to calculate spectrograms and plot them

** 0.5.1: Fast Channel analysis v1
- synthetic_signal_remap() inputs changed, now gmin, gmax, dg is now renamed as rmin, rmax, dr, to be consistent with the rest of the ScintillatorSuite
- *Bug solved* solves a bug in the synthetic_signal_remap() method, nan where appearing if the markers were outside the map range
- get_fast_channel() from the LibData now also returns the number of the loaded channel

** 0.5.0: New FILD remap
- The 'nearest' method of the interp_grid was deprecated
- The interp_grid method of the StrikeMap class was completely rewritten, please see the new function
- The remap method will call interp_grid of the smap object instead of failing if the grid was not interpolated before calling this function
- inputs for remap method of the mapping library was changed, now the edges of the histogram should be calculated outside (improve efficiency and easily allows for MC or standard remap switch)
- New MC remap based in the 'Translation Tensor' developed. See documentation PDF for a full description of the method

** 0.4.15 Profile routines and EHO tracker.
- Toroidal rotation reading routines has been included: from PED, IDI or make a smoothing spline to the CXRS raw data.
- Routines to read the profiles (electron temperature and density) from PED.
- EHO tracker with and without diamagnetic corrections has been included in Examples.
- Phase correction for the magnetic pick-up coils in AUG is now included.
- The phase correction files are automatically downloaded at the first time that the magnetic routines from AUG are run.


** 0.4.14: Smap and plotting improvements
- The StrikeMap object can now be initialised with the theta and phi angle, no longer need the full path to the file (although of course you can still use the file)
- If no file is given to the StrikeMap.load_strike_points() the code will look for the strike points file in the same folder than the strike map
- The substract noise function include now an option to make a copy of the frames or not (to save memory, dafult: True)
- Default plotting options now available via configurable namelist (Data/MyData)
- Minor ToDos solved
- Upgraded Readme


** 0.4.13: FILDSIM forward modeling
- Camera parameters no longer in LibParams but in separate txt files in the Data folders
- f90mnl is now a fundamental module, the suite will not work without it
- Added function in the LibIO to read the camera properties
- Current synthetic_signal and plot_synthetic signal function of the FILDSIM library renamed to synthetic_remap and plot_synthetic_remap
- *Note*: The weight function calculation does no longer include  * dr_scint * dp_scint, so the W has dimension of one over dgyr and dpitch of the scintillator grid used for the calculus
- Several plotting plotting capabilities added (credit to Ajvv)
- Routines to model basic camera noise added


** 0.4.12: Small improvements
- New examples for the tracker were added
- *Note*: The order of the inputs in the function write_markers for the tracker was changed, to follow the same logical order of the rest of the suite, now is: write_markers(markers: dict, filename: str)
- Small PEP8 stile corrections
- functions to save and read objects with pickles were added, this allows to save and load figures more or less as .fig from matlab (see save_object_pickle and load_object_pickle)
- Update run_paths.py to the new system to import modules
- function to read the deposition markers was added
- old method to write tracker namelist recoverd for legacy compatibility
- *Note*: the input of the LibIHIBPorbits, for the plot, is now 'ax_params' and 'line_params' instead of 'ax_options' and 'line_options', to be consistent with the rest of the suite
- *Note*: the input of the LibIHIBfields, to read the magnetic field from the database, now requiers shot and time instead of time and shot, to be consistend with the rest of the suite
- *Note*: same with readPsiPolfromDB
- *Note*: vt renamed to vphi in the properties of the markers

** 0.4.11: HotFix
- Fix an issue while importing library of BEB
- change '()' on the plot strike map for '[]' (all the rest of the plots of the suite indicate the units between [])

** 0.4.10: Tomography improvements
*** Tomography improvements
- Solved a bug in the process to W2D to W4D, last gyroradii was being ignored
- Now fildsim.build_weight_matrix() gives also the W2D matrix
- Lib.Tomography.prepare_X_y_FILD now can apply a median filter to the remap frame
- Forward modeled frame and profiles included in the Tomography GUI
*** NBI improvements
- Renamed _NBI_diaggeom_cordinates to NBI_diaggeom_cordinates
- The function NBI_diaggeom_coordinates include now the 'length' of the NBI line as well as the tangency point
- Included 'calculate_intersection' method in the NBI class to calculate the intersection points of the NBI line with the flux surfaces
- Included generate_tarcker_markers in the NBI class to generate markers for the tracer
*** Tracker changes
- The write namelist for the tracker was updated to the new f90mnl format adapted in the rest of the suite
- Duplicated tracker routines were eliminated, now only the iHIBPsim library should be used for the fields and orbits reading
- *DEPRECATED* The flag grid on the plotTimeTraces() of the orbit class was deprecated, if you want to plot the grid pass grid:'both' or 'major' to the ax_options dictionary
- plotTimeTraces() now has a flag to plot the R,Z,phi temporal evolution
- The routines to plot the orbits now admit a flag (default: True) to plot the vessel or not
- Added routine in the orbit class to calculate the gyrocenter coordinates
- Added the possibility of calculating the magnetic moment with the gyrocenter Bfield
*** Forward modeling improvements:
- Include check to avoid the forward modeling routine to give Nan when some points of the distribution are outside the range of the Strike map, these points will be ignored

** 0.4.8: Toroidal rotation fitting and hotfix for magnetic spectograms:
*** LibData
- Introduction of routines to read the toroidal rotation velocity from AUG database. Available profiles from IDI, PED and spline-regression to several CXRS diagnostics (CUZ, COZ, CMZ & CEZ).
*** Magnetics
- Ballooning coils phase correction for the FFT taken from pyspecview.
- All examples in FreqAnalysis corrected with the phase.

** 0.4.7: Support for BEP plotting:
- Added initial library for reading the calibrated and uncalibrated signal from BEP shotfiles.
- Simple GUI to plot interactively see the spectra for shots.
- Added few examples to plot the BEP in a non-interactive way.

** 0.4.6: FILDSIM orbit plotting:
- Orbit plotting included to plot FILDSIM calculated orbits

** 0.4.5: Bug solved:
- Solved a bug in the diaggeom coordinates for NBI8. NBI8 end was off by almost 10 cm

** 0.4.4: Import changes:
- Routes to libraries were change such that you can import the library just setting your environment variable in the path

** 0.4.3: i-HIBPsim strike line reader & Frequency tracking.
*** LibHIBPstrikes
- Adding support read and plot the strikelines from i-HIBPsim code.
- Added support to plot the scintillator synthetic signal.
- Added support to introduce the database of strike lines.
- Changed attributes in the database to adapt to a common TRANSP-like database. long_name contains a full description of the field while the short_name contains a ready-to-plot name.
*** LibFrequencyAnalysis
- Added STFT2 routine: wrapper to scipy implementation, emulating Giovanni's.
- Added iSTFT routine: wrapper to scipy implmentation, to reconstruct the signal from an STFT.
- Added Vertex and Graph classes, allowing for minimal path search (using Dijsktra's method).
- Added routine to search for frequency in a spectrogram (trackFrequency).
- Moved examples 'multipow', 'frequencyTracking' to new Folder: 'FrequencyAnalysis'
- New example to plot fast the spectrogram of a given magnetic pick-up coil.
*** Movement of LibDataAUG
- LibDataAUG is now moved inside the folder LibData, to allow for a smother integration of future machines

** 0.4.2: FILDSIM forward modeling
- Now the StrikeMap.calculate_resolutions() also calculate the interpolators so one can just call smap.interpolators['pitch']['sigma'](gyr0, pitch0) and you will have the interpolated value of sigma of the pitch for gyr0, pitch0.
- The StrikeMap object for FILD now include the fields: unique_gyroradius, unique_pitch and collimator_factor_matrix.
- *Included requested feature*: Issue #58: read_ASCOT_distribution implemented, only valid for ASCOT4
- Fits of the calculate resolution function are now inside the 'fits' dictionary, contained in the resolution section of the strike map object
- read_scintillator_efficiency moved from the LibIO to the new LibScintillatorCharacterization.py
- Efficiency included in FILD forward modeling
- Efficiency included in tomography
- Calculation of the W function for FILD re-written in a more compact way. Coherent with the models used to calculate the resolutions. Now it much faster
- fildsim.plot_geometry added in the fildsim library. It plot the plates geometry in 3d and is projections
- Method relating the absolute calibration of the frames removed from FILDSIM library, they'll be included again in next version once they are tested

** 0.4.1: Minor improvements + ELM filtering
- Added a function to calculate the intersection between any curves in 2D (LibUtilities.find_2D_intersection(x1, y1, x2, y2))
- Improved LibPlotting.plot_flux surfaces() : Now color can be selected, cm can be used as units, the axis limit will not be changed if an axis is given
- Included root directory of the suite in path_suite.py to be aable of using the command =import Lib as ss= outside the root directory of the suite
- Included reading of ELM time base (LibData.profiles.get_ELM_timebase.py)
- Included ELM filtering: Note, it will just delete from your input signal the ELM time points
- Read frame from a cin file will no longer return a squeeze matrix when you load the frames internally. When you load them externally, they will be squeeze()
- Solved issue #7: NBI profile calculation and plot upgraded
- Plot NBI added to the NBI class
- Now calc_pitch_profile of the NBI class take as default IpBt sign defined in the .dat library


** 0.4.0: New suite structure:
- Typos in comments corrected
- PEP8 agreement revised
- LibDataAUG subdivided in different modules (it was too big)
- Re-written first_run.py
- Verbose of remap_all_loaded_frames_FILD.py improved

** 0.3.6: Improvements in tomography:
- Now the Ridge, nnridge and Elastic net scan also return a dictionary with the produced figures

** 0.3.5: Bug solved:
- *Bug solved* Solved issue #54 on the broken time base of CCD cameras

** 0.3.4: First INPASIM utilities:
- GUIs files where divided into a new folder GUIs
- *Included requested feature*: Issue #33. Now if a path is passed to the remap routine mask=path the code will load the mask contained in file inidcated by path
- Included Non Negative Ridge as a regression method
- Included method to cut the video in the Video class, to restrict to a given region of pixels: Video.cut_frames()
- A flag was added in the noise_subtraction and filter methods of the Video class in order to decide if we want to create a copy of the experimental frames or not
- First methods to calculate optical transmission

** 0.3.3 i-HIBPsim strikeline and strikes reader:
- New library under iHIBPsim for reading and plotting strikelines and strikes on the scintillator.
- Added function in LibDataAUG for reading magnetic pick-up coils and group of them (same toroidal location).
- Added function in LibDataAUG for reading from the equilibrium the basics of the shot data (Bt0, Ip, elongation, ...)

** 0.3.2: First INPASIM utilities:
- Added function to fit a line to a 3d cloud of points
- Rewritten paths_suite.py to allow make easier to include new libraries

** 0.3.1: Tomography:
- Update examples to the new version
- Updated Smaps library (more maps) download the new version if you want
- video.find_orientation() added, allows to find the calculated theta and phi (Yes, I was lazy and I've created a small function to avoid the calculation of this manually)
- Now the same criteria of rmin, dr and so on is implemented in the tomographic reconstruction section
- Scan of tomographic reconstruction now gives a dict as output, not single outputs
- New GUI for tomographic representation plotted

** 0.3.0: GUIs and plotting
- Simplified StrikeMap.plot_pix() and StrikeMap.plot_real(). *IMPORTANT* Names of the input arguments were changed!!!
- Included GUI to explore the camera frames, Video.plot plot_frames_slider() was rename as Vide.GUI_frames()
- Included GUI to explore the remapped frames, Vide.GUI_frames_and_remap()
- Improved Video.plot_frame() was upgraded now you can write 'auto' and the function will load and plot the StrikeMap (see its documentation for further instructions)
- LibPlotting.remove_lines() added, it deletes all lines from a plot, useful to delete the strikemap of one of your plots (used by the new GUIs)
- *BUG SOLVED*: Selecting 'cancel' in the export remap windows raised and error. Now it solved

** 0.2.9 Multipow calculation.
- Included functions to read magnetic coils in LibDataAUG
- Included functions to read the ECE data in LibDataAUG.
- Included plotting function for the ECE data in LibPlotting
- Included plotting function for flux surfaces using contour levels.
- Solved hotfix for the 0.2.8
- Multipow (CPSD for magnetics-ECE) included as an Example/Others
- Included myCPSD calculation for cross-power calculation in LibFrequencyAnalysis.

** 0.2.8 i-HIBP cross sections.
- Included i-HIBP cross sections calculation and storing to files (Issue 34)

** 0.2.7: Hot fix
- *BUG_SOLVED* Problem with the name of the number of saturated pixels solved, now it is possible to export the remap again (the bug was introduced in version 0.2.6). Issue #50

** 0.2.6: Count pixels
- *Included requested feature*: Issue #50 now the number of pixels over a given threshold is counted by default. User can set this threshold in the read_frame method of the video object
- Video.plot_number_saturated_counts() added. If executed without arguments, it plot the pixels counted by default when reading the video. The function accept also a threshold, in this case the pixels are count again
- *BUG_SOLVED* The angles of rFILD are now properly included

** 0.2.5: Improvements in the remap
- Now when some Smap is missing, the program will give the option to use the nearest (in time) existing strike map
- The real value of theta (with all the decimals) as well as the used one are stored to compare the angles used in the remap
- Added plot_orientation() to the video object, to plot the calculated angles with the orientation (real and used)
- The method fildsim.write_namelist() now overwrite by default the existing namelist. You can change this behavior with the flag =overwrite=
- The method fildsim.guess_strike_map_name_FILD() now do not create extra strike maps like 0 and -0
- Camera model included as one more data in the FILD dictionary in LibDataAUG.py
- Some PEP8 correction in iHIBP library

** 0.2.4: HotFix
- *BUG_SOLVED* Solved bugs in the LibFILDSIM.find_strike_map routine, the fildsim options were not updated properly
- Updated FILDSIM example following new f90nml requirements

** 0.2.3: Filter for video object
- *Included requested feature*: median filter added to the filter_frames method of the video class (closes #47)
- *Closes #45* Now the rmin, rmax, pmin, pmax represent the output vector when we want the remap, not the input edges (:-()
- 'Clean' a bit the method 'find_strike_map' from the FILDSIM library, now a loop is used to run over FILDSIM namelist
- Included Gaussian filter for the video frames
- Reordered examples
- Simplified plotting options in TimeTrace.plot_single()
- Improved TimeTrace.plot_all(), now they share x axis so zoom is better

** 0.2.2: Debugging
- *BUG_SOLVED* in the plot_vessel function, the factor from m to cm was 10 instead of 100!
- *BUG_SOLVED* rotation of the vessel was not passed from the plot_vessel routine to the method which calculate the vessel coordinates
- *BUG_SOLVED* Solved bug when the requested interval to average the noise was not in the file (issue #46)

** 0.2.1: FIDASIM implementation
- First routines to read FIDASIM output added, (thanks Pilar :-)) Although some work still needed in that module this is not completely checked
- Updated Readme following nice example of iHIBP
- Calibration used in the remapping is saved in the remapping options, such that future comparisons of remapped data is easier
- plot_profiles_in_time of the video object allows now to pass the min and max of the scale as inputs
- *Included requested feature* First implementation of issue #41

** 0.2.0: Strike Maps reordering
- p1D_shaded_error updated with the possibility of plotting the central line
- Updated gitignore to ignore a folder call 'MyRoutines' for the user to have its own routines
- Updated the paths to strike maps, now two libraries will be used: Remap 'low' number of markers, 'Tomography' high number of markers
- Updated namelist format, now the suite follows the criteria given in the f90nml module
- Added GNU license

** 0.1.9: Spectrograms
- First spectrogram function added, first step towards the fast channel analysis
- Better examples included
- Better checking of whether we are in AUG or not
- Now the remapping of the whole shot can be done using a given strike map

** 0.1.8: Reverse FILD
- IB sign were included to include the proper pitch definition in FILDSIM even with the reverse field
- *BUG_SOLVED*: Solve a bug which forced the remap to ignore theta and phi if just one of the strike maps was not found
- Included the RealBPP in the exported remap data

** 0.1.7: Improve reading/writing
- Solved the issue in the init due to new iHIBPsim libraries
- Included a check to not overwrite files, now if one of the saving routines try to save a file which exist, it will open a window to give to the user the chance to change the name
- Added also a similar function to open files in case it does not find the name, it will pop-up a window
- Improved the checking to test we are in AUG
- Add a method to integrate the remapped frames in the desired range radius-pitch (arbitrary shapes allowed via roi)

** 0.1.6: What's new?
- Added possibility of loading the used ROIs
- Added the possibility of plotting each individual time trace
- Added general routine to load the created ncdf files
- Suppressed remapped slider plotting in the video object, it was too buggy, new one will come with tkinter

** 0.1.5: What's new?
- Now the remap_all_loaded_frames_FILD first calculate all theta and phi and see how many strike maps must be calculated. The user can decide whether if perform the FILDSIM calculation or just take a single strike map
- Added the possibility of remapping with a ROI. Also export the ROI

** 0.1.4: What is new?
- iHIBP routines to interact with the tracker and iHIBPsim, first round
