** 0.2.1: FIDASIM implementation
- First routines to read FIDASIM output added, (thanks Pilar :-)) Although some work still needed in that module this is not completelly checked
- Updated Readme following nice example of iHIBP
- Calibration used in the remapping is saved in the remapping options, such that future comparisons of remapped data is easier
- plot_profiles_in_time of the video object allows now to pass the min and max of the scale as inputs
- Solves issue #45

** 0.2.0: Strike Maps reordering
- p1D_shaded_error updated with the possibility of plotting the central line
- Updated gitignore to ignore a folder call 'MyRoutines' for the user to have its own routines
- Updated the paths to strike maps, now two libraries will be used: Remap 'low' number of markers, 'Tomography' high number of markers
- Updated namelist format, now the suite follows the criteria given in the f90nml module
- Added GNU license

** 0.1.9: Spectrograms
- First spectrogram function added, first step towards the fast channel analysis
- Better examples included
- Better checking of wether we are in AUG or not
- Now the remapping of the whole shot can be done using a given strike map

** 0.1.8: Reverse FILD
- IB sign were included to include the proper pitch definition in FILDSIM even with the reverse field
- *BUG_SOLVED*: Solve a bug which forced the remap to ignore theta and phi if just one of the strike maps was not found
- Included the RealBPP in the exported remap data

** 0.1.7: Improve reading/writting
- Solved the issue in the init due to new iHIBPsim libraries
- Included a check to not overwrite files, now if one of the saving routines try to save a file which exist, it will open a window to give to the user the chance to change the name
- Added also a similar function to open files in case it does not find the name, it will pop-up a window
- Improved the checking to test we are in AUG
- Add a method to integrate the remapped frames in the desired range radius-pitch (arbitrary shapes allowed via roi)

** 0.1.6: What's new?
- Added possibility of loadind the used ROIs
- Added the posibility of plotting each individual time trace
- Added general routine to load the created ncdf files
- Suppresed remapped slider plotting in the video object, it was too buggy, new one will come with tkinter

** 0.1.5: What's new?
- Now the remap_all_loaded_frames_FILD first calculate all theta and phi and see how many strike maps must be calculated. The user can decide wheter if perform the FILDSIM calculation or just take a single strike map
- Added the possibility of remaping with a ROI. Also export the ROI

** 0.1.4: What is new?
- iHIBP routines to interact with the tracker and iHIBPsim, first round
