* SCINTILLATOR SUITE 

This code is created to analyse the signal from scintillator diagnostics. Support for FILD, INPA and i-HIBp is planned. To include a different diagnostic, please contact Jose Rueda: jose.rueda@ipp.mpg.de 

** Prerequites 
Needed packages:

    - Numpy
    - Matplotlib
    - roipoly: To select ROIs in the image. The official package can be found here (https://github.com/jdoepfert/roipoly.py) but it does not work with SPYDER. Please use this fork instead (https://github.com/georgedeath/roipoly.py)

** Note for developers 
    - Indentation must be done via 4 spaces!
    - PEP 8 guide should be followed without exception autorished by all developers via the gitlab 'issues' page 

** Version control
Each release will be denoted by 3 numbers: a.b.c meaning:
    - c: bug fixed and improved comments and documentation. The higer the number, the better
    - b: include new optional capabilities, versions a.b1.c1 and a.b2.c2, should run perfectly with the same inputs. The higher b, the more extra capabilities you have
    - a: indicate major changes in the code, versions with different 'a' may be not compatible
