* SCINTILLATOR SUITE

This code is created to analyse the signal from scintillator diagnostics. Support for FILD, INPA and i-HIBp is planned. To include a different diagnostic, please contact Jose Rueda: jose.rueda@ipp.mpg.de

** Prerequites
Needed packages:
Only listed 'non-standard' packages
    - roipoly: To select ROIs in the image. The official package can be found here <https://github.com/jdoepfert/roipoly.py> but it does not work with SPYDER. Please use this fork instead (https://github.com/georgedeath/roipoly.py)

** Note for developers
    - Indentation must be done via 4 spaces!
    - PEP 8 guide should be followed without exception autorished by all developers via the gitlab 'issues' page

** Version control
Each release will be denoted by 3 numbers: a.b.c meaning:
    - c: bug fixed and improved comments and documentation. The higer the number, the better
    - b: include new optional capabilities, versions a.b1.c1 and a.b2.c2, should run perfectly with the same inputs. The higher b, the more extra capabilities you have
    - a: indicate major changes in the code, versions with different 'a' may be not compatible

** FILDSIM notes
- You need to create an empty folder in the root of FILDSIM code with name 'cfg_files' in order to run the remap routine

** Paths
- The paths of the suite are hardcored in the file paths_suite.py. If you have FILDSIM, INPASIM and everyting installed in your home folder (strongly recomended), things should work, if not... you will have to modify this file yourself
- IMPORTANT: In order to determine in which machine we are running this, the code will search in the path name, for example, if the path is /afs/ipp/... the suite will consider you are in ASDEX. Please do not execute the code for SMART in a folder called IPP or the program will be crazy

** Machine names
All devices are identified by three letters:
- 'AUG': ASDEX Upgrade

** Useful links
- FILDSIM code: <https://gitlab.mpcdf.mpg.de/jgq/FILDSIM.git>
- INPASIM code: <https://gitlab.mpcdf.mpg.de/ruejo/inpasim.git>
- i-HIBPSIM code: <https://gitlab.mpcdf.mpg.de/poyo/fosd.git>

** Complete docmentation
- The routines in the Example folder are intended to ilustrate the use of the different tools in the suite
- For a Doxygen generated documentation, see: <https://hdvirtual.us.es/discovirt/index.php/s/FBjZ9FPfjjwMDS2> download the content and open the index.html file, inside the html folder
