"""
Strikeline library for the data analysis of the iHIBP scintillator.

Pablo Oyola - pablo.oyola@ipp.mpg.de
"""

import os
import numpy as np
import warnings
import matplotlib.pyplot as plt
import scipy.interpolate as scipy_interp
import Lib.LibPlotting as ssplt
from Lib.LibMap.Common import XYtoPixel
import Lib.SimulationCodes.iHIBPsim as ihibpsim
from Lib.LibMachine import machine
import Lib.LibPaths as p
pa = p.Path(machine)
del p


class StrikeLine(XYtoPixel):
    """
    This class handles strikeline mapping the scintillator into the variable
    rhopol.
    """

    def __init__(self, path: str = None):
        """
        Initializes the strikeline class.

        Pablo Oyola - pablo.oyola@ipp.mpg.de
        """

        ## Init the parent class
        super().__init__()

        ## Setting up dummy data.
        self.y = None
        self.z = None

        ## Retrieve the data of the strikeline.
        self.path = path
        if path is not None:
            if not os.path.isfile(path):
                raise FileNotFoundError('Cannot find the file with the '+
                                        ' strike line data: %s'%path)

            self.load_from_file(path)

    def load_from_file(self, path: str):
        """
        This will load the strikemaps from the .map file generated by
        the iHIBPsim code.

        Pablo Oyola - pablo.oyola@ipp.mpg.de

        @param path: path to the file.
        """
        self.mapdata = ihibpsim.strikes.strikeLine(filename=path)

        ## With the loaded map, we set the coordinates (y, z)