* FILD ANALYSIS EXAMPLES

These routines should serve as an example of the main FILD data analysis you can perform with the ScintillatorSuite. Of course several small options and auxiliary plotting capabilities are not included in these examples, but they should give a good overview. Please ask jrrueda@us.es if you want further examples

*DO NOT* change parameters in the examples, as this could cause merge request in the future. If you want to adapt your files to your shots, please copy them to MyRoutines folder!

** Pre-requites
run always paths_suite.py before running these examples

** Examples
  - L0: Use and interact with FILD logbook
  - L1: Load a video from FILD
  - L2: Load a video and calculate the time trace, this is not the recommended method if you want to calculate a TT of a .cin video, as it load all the video before calculating the timetrace. For Cin videos, please see a follow up example
  - L3: Load the FILD video and average its frames
  - L4: Remap a whole video.
  - L5: Remap a whole video but using a roi to limit a region in the scintillator
  - L6: Remap the whole video but using the same strike map
  - L7: Calculate a time trace, optimized for the case of a .cin file
  - L8: Example of remap a single frame, compares MC and 'typical' (centroid) remap
  - L9: Example of how to compare 2 plots from the camera and their remaps, ideal for MMM
  - L10: Tomographic inversion of a frame
  - L11: Plot the fast channel signals from FILD
  - L12: Calculate and compare CCD timetraces
  - L13: Calculate and compare Phanton timetraces (L12 could also be used, but this one is optimised for long files)
  - L15: Perform a tomographic inversion, but just for the gyroradius (integrate in pitchangle)
